baseURL: https://danaukes.com/
languageCode: en-us
title: Dan Aukes
theme:
- liva-hugo
ignorefiles:
  - ignore/*
taxonomies:
  category: categories
  tag: tags
  recipe_tag: recipe_tags
disqusShortname: ''
languageCode: en-us
#menu:
#  footer:
#  - URL: about
#    name: About
#    weight: 1
#  main:
#  - URL: notebook
#    name: Notebook
#    weight: 4
outputs:
  home:
  - HTML
  - RSS
  - JSON
paginate: 6
params:
  github_repo: "https://github.com/danb0b/danb0b.github.io"
  github_edit_branch: master
  default_icon: bi bi-file-text
  default_recipe_icon: bi bi-cup
  formspree: https://formspree.io/f/mayadavw
  HideDate: true
  author: Dan Aukes
  cookies:
    enable: false
    expire_days: 2
  copyright: "|  copyright &copy; 2021 Daniel Aukes.  All Rights Reserved.  |"
  description: This is meta description
  #email: 'danaukes at gmail.com'
  #googleAnalitycsID: Your ID
  home: Home
  location: Arizona, USA
  logo: da-small.png
#  mobile: 0124857985320
  newsletter:
    content: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
      eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
      At vero
    enable: false
    title: Join Our Newsletter
  plugins:
    css:
    - URL: plugins/bootstrap/bootstrap.min.css
    - URL: plugins/slick/slick.css
    - URL: plugins/themify-icons/themify-icons.css
    - URL: plugins/venobox/venobox.css
    - URL: https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css
    js:
    - URL: plugins/jQuery/jquery.min.js
    - URL: plugins/bootstrap/bootstrap.min.js
    - URL: plugins/slick/slick.min.js
    - URL: plugins/venobox/venobox.min.js
    - URL: plugins/search/fuse.min.js
    - URL: plugins/search/mark.js
    - URL: plugins/search/search.js
  preloader:
    enable: true
    preloader: ''
  search:
    enable: true
  social:
#  - icon: ti-facebook
#    link: '#'
#    title: facebook
  - icon: ti-twitter-alt
    link: 'https://twitter.com/danaukes'
    title: twitter
#  - icon: ti-instagram
#    link: '#'
#    title: instagram
  - icon: ti-github
    link: 'https://github.com/danb0b'
    title: personal github
  - icon: ti-linkedin
    link: 'https://www.linkedin.com/in/dan-aukes-502995212/'
    title: linkedin

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: monokailight
    noClasses: true

summarylength: 10

