baseURL: https://www.danaukes.com
languageCode: en-us
title: Dan Aukes
theme:
- liva-hugo
ignorefiles:
  - ignore/*
taxonomies:
  category: categories
  tag: tags
  recipe_tag: recipe_tags
disqusShortname: ''
menu:
  footer: []
  # - URL: https://idealab-asu.slack.com
  #   name: IDEAlab Slack
  #   weight: 1
  # - URL: https://scram-workspace.slack.com
  #   name: SCRAMbots
  #   weight: 2
  # - URL: https://kaiteki-asu.slack.com
  #   name: Kaiteki
  #   weight: 3
  main:
  - name: Misc
    weight: 99
outputs:
  home:
  - HTML
  - RSS
  - JSON
pagination:
  pagerSize: 6
params:
  github_repo: "https://github.com/danb0b/danb0b.github.io"
  github_edit_branch: master
  default_icon: bi bi-file-text
  default_recipe_icon: bi bi-cup
  formspree: https://formspree.io/f/mayadavw
  HideDate: true
  author: Dan Aukes
  cookies:
    enable: false
    expire_days: 2
  copyright: "|  copyright &copy; 2025 Daniel Aukes.  All Rights Reserved.  |"
  description: Dan Aukes' personal website
  home: Home
  location: Arizona, USA
  logo: da-small.png
  plugins:
    css:
    - URL: plugins/glightbox/css/glightbox.css
    - URL: plugins/bootstrap/bootstrap.min.css
    - URL: plugins/slick/slick.css
    - URL: plugins/themify-icons/themify-icons.css
    - URL: plugins/venobox/venobox.css
    - URL: https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css
    js:
    - URL: plugins/glightbox/js/glightbox.js
    - URL: plugins/jQuery/jquery.min.js
    - URL: plugins/bootstrap/bootstrap.min.js
    - URL: plugins/slick/slick.min.js
    - URL: plugins/venobox/venobox.min.js
    - URL: plugins/search/fuse.min.js
    - URL: plugins/search/mark.js
    - URL: plugins/search/search.js
  preloader:
    enable: true
    preloader: ''
  search:
    enable: true
  social:
  - icon: ti-github
    link: 'https://github.com/danb0b'
    title: personal github
  - icon: ti-linkedin
    link: 'https://www.linkedin.com/in/dan-aukes-502995212/'
    title: linkedin
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: monokailight
    noClasses: true
summarylength: 5
